local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.wrap = false
opt.swapfile = false
opt.backup = false
opt.undodir = vim.fn.stdpath("data") .. "/undodir"
opt.undofile = true
opt.hlsearch = false
opt.incsearch = true
opt.termguicolors = true
opt.scrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 50
-- opt.colorcolumn = "100"
opt.clipboard = "unnamedplus"
opt.splitright = true
opt.splitbelow = true
opt.cursorline = true
opt.ignorecase = true
opt.smartcase = true
opt.pumheight = 10
